# Default values for 5gcore-helm.

open5gcore:
  image:
    repository: quay.io/adetalho/open5gs
    pullPolicy: IfNotPresent
    tag: "v1.1"

webui:
  enabled: true
  image:
    repository: docker.io/efatnar/open5gcore-webui
    pullPolicy: IfNotPresent
    tag: "v1.1"

dnn: internet  

k8s:
 interface: eth0

amf:
  enabled: true
  mcc: 208
  mnc: 93
  tac: 7
  serviceName: open5gs-amf
bsf:
  enabled: true
ausf:
  enabled: true
mongo:
  enabled: true
nrf:
  enabled: true
  serviceName: open5gs-nrf
nssf:
  enabled: true
pcf:
  enabled: true
  serviceName: open5gs-pcf
udm:
  enabled: true
  serviceName: open5gs-udm
udr:
  enabled: true
upf:
  enabled: true
  serviceName: open5gs-udm
smf:
  enabled: true
  serviceName: open5gs-smf
