{{ if .Values.amf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: amf-open5gs-sctp
  labels:
    epc-mode: amf
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - protocol: SCTP
      port: 38412
      targetPort: 38412
      nodePort: 30412
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  annotations:
    skupper.io/proxy: http2
    skupper.io/address: open5gs-amf-shared
  labels:
    epc-mode: amf
spec:
  type: NodePort
  selector:
    epc-mode: amf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf-d
  labels:
    epc-mode: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
    spec:    
      containers:
        - name: amf
          image: "{{ .Values.open5gcore.image.repository }}:{{ .Values.open5gcore.image.tag }}"
          imagePullPolicy: {{ .Values.open5gcore.image.pullPolicy }}
          ports:
            - containerPort: 38412
              name: amf-sctp
              protocol: SCTP
          securityContext:
            privileged: true
          command: ["open5gs-amfd", "-d", "-c", "/open5gs/config-map/amf.yaml"]
          volumeMounts:
          - name: open5gs-amf-config
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: open5gs-amf-config
          configMap:
            name: open5gs-amf-config
{{ end }}
