{{ if .Values.mongo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-ca
  namespace: open5gcore
type: Opaque
data:
{{ tpl (.Files.Glob "resources/*").AsSecrets . | indent 2 }}
{{ end }}