{{ if .Values.nrf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: open5gs-nrf
  annotations:
    skupper.io/proxy: http2
    skupper.io/address: open5gs-nrf-shared
  labels:
    epc-mode: nrf
spec:
  selector:
    epc-mode: nrf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nrf-d
  labels:
    epc-mode: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nrf
  template:
    metadata:
      labels:
        epc-mode: nrf
    spec:  
      containers:
        - name: nrf
          image: "{{ .Values.open5gcore.image.repository }}:{{ .Values.open5gcore.image.tag }}"
          imagePullPolicy: {{ .Values.open5gcore.image.pullPolicy }}
          securityContext:
            privileged: true
          command: ["open5gs-nrfd", "-d", "-c", "/open5gs/config-map/nrf.yaml"]
          volumeMounts:
            - name: open5gs-nrf-config
              mountPath: /open5gs/config-map/nrf.yaml
              subPath: "nrf.yaml"
      volumes:
        - name: open5gs-nrf-config
          configMap:
            name: open5gs-nrf-config

{{ end }}