{{ if .Values.pcf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    #logger:
       #file: /var/log/open5gs/pcf.log
    db_uri: mongodb://mongodb-svc/open5gs    
    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: {{ .Values.pcf.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
    nrf:
     sbi:
      name: open5gs-nrf.{{ .Release.Namespace }}.svc.cluster.local
{{ end }}