apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5gcore
  namespace: telco-gitops
spec:
  destination:
    name: in-cluster
    namespace: open5gcore
    server: ''
  source:
    path: 5gcore
    repoURL: 'https://github.com/williamcaban/open5gs-helm-chart'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

