apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open5gran
  namespace: open5g-gitops
spec:
  destination:
    name: in-cluster
    namespace: open5gran
    server: ''
  source:
    path: 5gran
    repoURL: 'https://github.com/openshift-telco/open5gs-helm-chart'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

