apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv7
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /kvm-nfs/pv7
    server: 192.168.1.15
